<?xml version="1.0" encoding="utf-8"?><Database Name="mbp" Class="mbpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PROPIETARIO-PC\SQLEXPRESS;Initial Catalog=mbp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mbpConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.prods" Member="prods">
    <Type Name="prod">
      <Column Name="ARTICULO" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DESCRIP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LINEA" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="MARCA" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PRECIO1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO4" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO5" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO6" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO7" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO8" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO9" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO10" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EXISTENCIA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="COSTO_U" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="COSTO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UNIDAD" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POR_RECIB" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="POR_SURT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IMPUESTO" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MINIMO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MAXIMO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OBSERV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COSTO_STD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="KIT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SERIE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="LOTE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INVENT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IMAGEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PARAVENTA" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Curso" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="USUARIO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="USUHORA" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="USUFECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Exportado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="EN_VENTA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Recalcular" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Granel" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Peso" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="BajoCosto" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Bloqueado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="U1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U4" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U5" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U6" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U7" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U8" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U9" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="U10" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Acaja" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICAPRECIO" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Fraccionario" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IESPECIAL" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UBICACION" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="C2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C4" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C5" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C6" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C7" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C8" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C9" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="C10" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Movimientos" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Clasificacion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ROP" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="rotacion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="clasifant" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="eoq" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="etiquetas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modelo" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="talla" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="speso" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="etiqueta" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="carton" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ubicaetiq" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="unidadrecibe" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="unidadempaque" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sinvolumen" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Presentacion" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Servicio" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="numeroservicios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="claveproveedor" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="dp" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="familia" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="subfamilia" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="subfam1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="subfam2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Entradas" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Salidas" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cantent" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cantsal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="pronostico" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="oferta" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="costoentrada" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="costosalida" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="unidadesentrada" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="unidadessalida" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="donativo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="costopeps" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="costoueps" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="contenido" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="presentacionextra" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="pesoextra" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="autor" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="tema" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="editorial" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fabricante" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="preciousd" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="costousd" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="puntos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="autocodigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="inventariopiezas" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="diasstockmaximo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="diasstockminimo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="requerimiento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tiempoAire" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="ensambladoenlinea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iepslitro" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="numerodeselecciones" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.partvta" Member="partvtas">
    <Type Name="partvta">
      <Column Name="VENTA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIPO_DOC" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="serieDocumento" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NO_REFEREN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ARTICULO" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CANTIDAD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="COSTO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DESCUENTO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IMPUESTO" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="OBSERV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PARTIDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_SALIDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UsuFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuHora" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="ALMACEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LISTA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PRCANTIDAD" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="PRDESCRIP" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="PrecioBase" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Autorizado" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Caja" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Devolucion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DevConf" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ID_entrada" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Invent" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="importe" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="kit" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="costo_u" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="iespecial" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="puntadas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colores" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="verificado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="donativo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="A01" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lote" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="iepslitro" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="FactCierre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="venta_partvta" Member="venta1" ThisKey="VENTA" OtherKey="VENTA" Type="venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ventas" Member="ventas">
    <Type Name="venta">
      <Column Name="VENTA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OCUPADO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TIPO_DOC" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="serieDocumento" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="NO_REFEREN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F_EMISION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_VENC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CLIENTE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="VEND" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IMPORTE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESCUENTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IMPUESTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRECIO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COSTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ALMACEN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="OBSERV" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TIPO_CAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MONEDA" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DESC1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESC2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESC3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESC4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESC5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DATOS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ENFAC" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="VENTAREF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CIERRE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="cierretienda" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DESGLOSE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COBRANZA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USUARIO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="USUFECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USUHORA" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="AUTO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Relacion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PEDCLI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PEMB" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="DATEMB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AplicarDes" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Exportado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUCURSAL" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="VentaSuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pago1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Pago2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Concepto1" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Concepto2" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Pago3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Concepto3" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Comision" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VentaOrigen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diario" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Caja" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrigenDev" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Corte" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Impreso" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="BANCO" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NumeroCheque" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="estacion" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="interes" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="redondeo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ticket" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="importar" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sucremota" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ventaremota" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comodin" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="iespecial" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nodesglosedetalle" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Transporte" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Repartidor" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="horasalida" Type="System.String" DbType="NVarChar(19)" CanBeNull="true" />
      <Column Name="horaregreso" Type="System.String" DbType="NVarChar(19)" CanBeNull="true" />
      <Column Name="comisiontel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="verificado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="donativo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pagado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="comisionvendedor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="comodin1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="comodin2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="comodin3" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="comodin4" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="pago4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="concepto4" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="pregunta1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pregunta2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pregunta3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pregunta4" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pregunta5" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="fechacierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="businessintelligence" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="pedido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cambioDeEstado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="placas" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="kilometraje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="serie" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="motor" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="marca" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="modelo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horaentrega" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="propina" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="paraconcentrador" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="FE_Emitir" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FE_Fecha" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FE_Serie" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FE_Folio" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FE_Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="facturaelectronica" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="facturado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="seriefactura" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="foliofactura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="archivoFE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tocken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="noAprobacion" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="importeletra" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="foliocaducidad" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="pedimentos" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UUID" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ComprobanteXML" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="venta_partvta" Member="partvtas" ThisKey="VENTA" OtherKey="VENTA" Type="partvta" />
    </Type>
  </Table>
  <Table Name="dbo.clients" Member="clients">
    <Type Name="client">
      <Column Name="CLIENTE" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CALLE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NUMERO" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="COLONIA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="POBLA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CIUDAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAIS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIAS" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CREDITO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DESC1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DESC2" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DESC3" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DESC4" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DESC5" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RFC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CONTACTO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COBRADOR" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VEND" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PRECIO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="PROSPECT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="REVISION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OBSERV" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ZONA" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SALDO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="USUARIO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="USUHORA" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="USUFECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PROVEEDOR" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CURB" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CORTE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COBRO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CONCEPTO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="INGRESO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bloqueado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="claveweb" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="emailcobranza" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="embarcar" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="foto" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="puntos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="recomendado" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="comision" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="nuevo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="localidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="numerointerior" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="numeroexterior" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.impuestos" Member="impuestos">
    <Type Name="impuesto">
      <Column Name="Impuesto" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Descrip" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="usuFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usuHora" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="componente1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="componente2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="componente3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="componente4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="componente5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuario">
      <Column Name="USUARIO" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AREA" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DERECHOS" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FOTO" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SUPERVISOR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ACTIVOS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SACAR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Opera" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FACTURAR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COBRAR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="FACTURAS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DEVOLUC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAGOS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COTIZA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COBRANZA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAMFECHA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NUMPOLIZA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PERIODOS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MODIFICAPRECIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Existencia" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="existsalidas" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="gerenciales" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vendedor" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="surtirpedidos" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cobrador" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="idTeller" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.clavesadd" Member="clavesadds">
    <Type Name="clavesadd">
      <Column Name="Clave" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dato1" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usuFecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="usuHora" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Dato2" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Articulo" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Unidad" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Existencia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Libre" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Exportado" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="imagen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="etiquetas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.vends" Member="vends">
    <Type Name="vend">
      <Column Name="Vend" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comision" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="usuFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usuHora" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="foraneo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>